# This is a basic workflow to help you get started with Actions

name: Bonify-Automates-Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: step1-cheking out the master branch of Bonify-Test
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: step2-install JDK 1.8
        uses: actions/setup@javav1
        with:
          java-version: 1.8
          
          
      - name: step3-run automated tests 
        run: mvn clean test --file pom.xml
      
      
      - name: step4-view test automation report
        run: |
         cd target
         ls -a
        

 
